
default_platform :android

platform :android do

  desc "Take screenshots"
  lane :screenshot do
    gradle(
      task: 'clean assembleDebug assembleAndroidTest'
    )

    sh("adb shell pm grant com.redditgifts.mobile android.permission.WRITE_EXTERNAL_STORAGE")
    sh("adb shell pm grant com.redditgifts.mobile android.permission.READ_EXTERNAL_STORAGE")

    apk_path = Dir.glob("../**/*-debug.apk").first
    test_apk_path = Dir.glob("../**/*-debug-androidTest.apk").first

    screengrab(
      app_package_name: 'com.redditgifts.mobile',
      app_apk_path: File.absolute_path(apk_path),
      tests_apk_path:  File.absolute_path(test_apk_path)
    )
  end

  desc "Deploy to PlayStore Beta"
  lane :beta do
    gradle(
      task: 'test'
    )

    gradle(
      task: 'clean'
    )

    gradle(
      task: 'bundle',
      build_type: 'Release'
    )

    puts "AABs: #{Actions.lane_context[SharedValues::GRADLE_ALL_AAB_OUTPUT_PATHS]}"
    puts "AAB: #{Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"

    supply(
      package_name: "com.redditgifts.mobile",
      track: "beta",
      json_key: "app/upload.json",
      aab: "app/build/outputs/bundle/release/app.aab",
      metadata_path: "fastlane/metadata/android",
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_apk: true,
      skip_upload_aab: false
    )
  end

  desc "Move change logs into release notes"
  lane :prepare_release_notes do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )

    androidVersion = get_android_version(apk: "app/build/outputs/apk/release/app-release.apk")
    name = lane_context[SharedValues::GET_ANDROID_VERSION_NAME]
    code = lane_context[SharedValues::GET_ANDROID_VERSION_CODE]
    stamp_changelog(
      section_identifier: name, # Specify identifier to stamp the Unreleased section with
      git_tag: 'master' # Specify reference to git tag associated with this section
    )
    sh("sed -i '' -e '$ d' ../CHANGELOG.md")
    changelog = read_changelog(
                  changelog_path: 'CHANGELOG.md',	# Specify path to CHANGELOG.md
                  section_identifier: "[#{name}]"	# Specify what section to read
                  # excluded_markdown_elements: ['-', '###']	# Specify which markdown elements should be excluded
                )
    metadata_dir="metadata/android/en-GB/changelogs"
    sh("rm -rf #{metadata_dir}/*")
    sh("cat <<EOT >> #{metadata_dir}/#{code}.txt
#{changelog}")
    sh("sed -i '' -e '$ d' #{metadata_dir}/#{code}.txt")

  end

end
